spring:
  rabbitmq:
    host: 176.122.166.247
    port: 5672
    username: guest
    password: guest
  redis:
    database: 1
    host: 118.89.183.89
    port: 6379
    password: snaildy123
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 1000
  mail:
    host: smtp.163.com
    port: 465
    username: su18995636120@163.com
    password: OHNZJMHQUPWTSGYX
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mq:
  exchange: logMessage.direct
  info:
    routerKey: infoKey
    queue: info
  error:
    routerKey: errorKey
    queue: error