spring:
  rabbitmq:
    host: 176.122.166.247
    port: 5672
    username: guest
    password: guest
  redis:
    database: 1
    host: 118.89.183.89
    port: 6379
    password: snaildy123
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 1000
mq:
  exchange: logMessage.direct
  info:
    routerKey: infoKey
    queue: info
  error:
    routerKey: errorKey
    queue: error