spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.56.146.107:3306/housekeeping?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: snaildy123
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 47.56.146.107
    port: 5672
    username: guest
    password: guest
  redis:
    database: 1
    host: 47.56.146.107
    port: 6379
    password: snaildy123
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 1000
  mail:
    host: smtp.qq.com
    username: 1213225994@qq.com
    password: iyhijjjyvqxkifie
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mq:
  exchange: logMessage.direct
  info:
    routerKey: infoKey
    queue: info
  error:
    routerKey: errorKey
    queue: error
oss:
  endpoint: http://oss-cn-shanghai.aliyuncs.com
  accessKeyId: UAlClM+FccyHfzGjBX5Njx8kB9Ww/4zb
  accessKeySecret: wJCEnxvmPFxBzvw4QaPFM7clYNLZFE0NOKyn9y1sV10=
  bucketName: test-live-video
  urlPrefix: https://test-live-video.oss-cn-shanghai.aliyuncs.com/